package com.redhat.demo.aml_rules;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CustomerInIndustryList implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String industry;

	public CustomerInIndustryList() {
	}

	public java.lang.String getIndustry() {
		return this.industry;
	}

	public void setIndustry(java.lang.String industry) {
		this.industry = industry;
	}

	public CustomerInIndustryList(java.lang.String industry) {
		this.industry = industry;
	}

}