package com.redhat.demo.aml_rules;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CustomerInHighRiskCountry implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String country;

	public CustomerInHighRiskCountry() {
	}

	public java.lang.String getCountry() {
		return this.country;
	}

	public void setCountry(java.lang.String country) {
		this.country = country;
	}

	public CustomerInHighRiskCountry(java.lang.String country) {
		this.country = country;
	}

}