package com.redhat.demo.aml_rules;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class RuleResult implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String message;

	public RuleResult() {
	}

	public java.lang.String getMessage() {
		return this.message;
	}

	public void setMessage(java.lang.String message) {
		this.message = message;
	}

	public RuleResult(java.lang.String message) {
		this.message = message;
	}

}