package com.redhat.demo.aml_rules;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class RuleResult implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public RuleResult() {
    }




}